# Project
version=0.10.0
group=com.mrbysco.distantfriends

# Common
minecraft_version=1.21.5
neoform_version=1.21.5-20250325.162830
parchment_minecraft_version=1.21.5
parchment_mapping_version=2025.06.01

# NeoForge
neo_version=21.5.90

# Fabric
fabric_version=0.128.2+1.21.5
fabric_loader_version=0.17.2
cloth_config_version=18.0.145
mod_menu_version=14.0.0-rc.2

# Mod options
mod_name=DistantFriends
mod_author=Mrbysco
mod_id=distantfriends

#Publishing
curseforge_id=839197
modrinth_id=CDaJ8xGu

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false