# Project
version=0.11.0
group=com.mrbysco.distantfriends

# Common
minecraft_version=1.21.8
neoform_version=1.21.8-20250717.133445
parchment_minecraft_version=1.21.8
parchment_mapping_version=2025.07.20

# NeoForge
neo_version=21.8.32

# Fabric
fabric_version=0.132.0+1.21.8
fabric_loader_version=0.17.2
cloth_config_version=19.0.147
mod_menu_version=15.0.0-beta.3

# Mod options
mod_name=DistantFriends
mod_author=Mrbysco
mod_id=distantfriends

#Publishing
curseforge_id=839197
modrinth_id=CDaJ8xGu

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false