# Project
version=0.13.0
group=com.mrbysco.distantfriends

# Common
minecraft_version=1.21.10
neoform_version=1.21.10-20251007.142004
parchment_minecraft_version=1.21.9
parchment_mapping_version=2025.10.05

# NeoForge
neo_version=21.10.8-beta

# Fabric
fabric_version=0.135.0+1.21.10
fabric_loader_version=0.17.3
cloth_config_version=20.0.148
mod_menu_version=16.0.0-rc.1

# Mod options
mod_name=DistantFriends
mod_author=Mrbysco
mod_id=distantfriends

#Publishing
curseforge_id=839197
modrinth_id=CDaJ8xGu

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false